<?php defined('BASEPATH') OR exit('No direct script access allowed');

/**
 * Modèles chargés par contrôleur (généré depuis l'usage de $this->m_*).
 * Complété par MY_Loader pour les modèles utilisés uniquement dans les vues.
 */
return array(
    'Arretcaisses' => array(
        'm_compte_user',
        'm_depense',
        'm_depot',
        'm_entreprises',
        'm_recette',
        'm_typedocument',
        'm_versements',
    ),
    'Banques' => array(
        'm_banque',
        'm_compagnies',
        'm_entreprises',
    ),
    'Bon_Millitaire' => array(
        'm_bon_millitaire',
        'm_client',
        'm_compte_user',
        'm_entreprises',
        'm_sousgare',
    ),
    'Bus' => array(
        'm_bus',
        'm_categories',
        'm_compagnies',
        'm_entreprises',
    ),
    'Caissescourriers' => array(
        'm_categ',
        'm_client',
        'm_code_courrier',
        'm_compagnies',
        'm_compte_user',
        'm_courrier_expedier',
        'm_entreprises',
        'm_facturation',
        'm_gare_depart',
        'm_lignes',
        'm_sousgare',
        'm_typecontrat',
    ),
    'Caisses' => array(
        'm_banque',
        'm_caisse',
        'm_compagnies',
        'm_comptes_bagage',
        'm_comptes_courrier',
        'm_comptes_guichet',
        'm_compte_user',
        'm_depense',
        'm_depot',
        'm_entreprises',
        'm_escalclients',
        'm_gare_depart',
        'm_genre_depense',
        'm_genre_depot',
        'm_genre_recette',
        'm_non_passager',
        'm_passager',
        'm_personnels',
        'm_recette',
        'm_report',
        'm_sousgare',
        'm_type_client',
        'm_typedocument',
        'm_type_personnel',
        'm_versements',
    ),
    'Cartes_Voyage' => array(
        'm_carte_ligne',
        'm_carte_voyage',
        'm_client',
        'm_compte_credite',
        'm_compte_user',
        'm_entreprises',
        'm_lignes',
        'm_sousgare',
    ),
    'Categories' => array(
        'm_categories',
        'm_categories_siege',
        'm_entreprises',
    ),
    'Compagnies' => array(
        'm_compagnies',
        'm_entreprises',
        'm_pays',
        'm_villes',
    ),
    'Comptecaisses' => array(
        'm_bagage',
        'm_bagageesc',
        'm_compagnies',
        'm_comptes_bagage',
        'm_comptes_courrier',
        'm_comptes_courrierrecet',
        'm_compte_user',
        'm_courrier_expedieresc',
        'm_entreprises',
        'm_gare_depart',
        'm_sousgare',
    ),
    'Confirmation' => array(
        'm_bagage',
        'm_bagageesc',
        'm_bon_millitaire',
        'm_bordereaubagage',
        'm_carte_voyage',
        'm_categ',
        'm_client',
        'm_compagnies',
        'm_compte_credite',
        'm_compte_user',
        'm_courrier_expedier',
        'm_courrier_expedieresc',
        'm_entreprises',
        'm_envoibagages',
        'm_gare_arrivee',
        'm_gare_depart',
        'm_heure',
        'm_itineraire',
        'm_ligne_heure',
        'm_lignes',
        'm_ordres',
        'm_passager',
        'm_personnels',
        'm_programme',
        'm_quartier',
        'm_recepteur',
        'm_sousgare',
        'm_tamponcode',
        'm_tamponcodetr',
        'm_tampon_siege',
        'm_type_client',
        'm_valeurattrib',
        'm_valeurs',
        'm_itineraire_etape',
    ),
    'Depenses' => array(
        'm_caisse',
        'm_client',
        'm_compagnies',
        'm_compte_user',
        'm_depense',
        'm_depot',
        'm_entreprises',
        'm_genre_depense',
        'm_personnels',
        'm_sousgare',
        'm_typedocument',
        'm_type_personnel',
        'm_versements',
    ),
    'Depots' => array(
        'm_banque',
        'm_depot',
        'm_entreprises',
        'm_genre_depot',
        'm_typedocument',
        'm_versements',
    ),
    'Documentation' => array(
        'm_entreprises',
    ),
    'Param_restrictions' => array(
        'm_entreprises',
        'm_gare_depart',
    ),
    'Audit_quotidien' => array(
        'm_entreprises',
    ),
    'Rapport_autre_vente' => array(
        'm_entreprises',
    ),
    'Rapport_modif_ticket' => array(
        'm_entreprises',
    ),
    'Entreprises' => array(
        'm_entreprises',
        'm_pays',
        'm_villes',
    ),
    'Etatfactures' => array(
        'm_courrier_expedier',
        'm_entreprises',
        'm_facturation',
        'm_gare_depart',
    ),
    'Gares' => array(
        'm_bagage',
        'm_caisse',
        'm_categ',
        'm_categories',
        'm_client',
        'm_compagnies',
        'm_compte_user',
        'm_entreprises',
        'm_escalclients',
        'm_gare_arrivee',
        'm_gare_depart',
        'm_gares',
        'm_heure',
        'm_ligne_heure',
        'm_lignes',
        'm_non_passager',
        'm_passager',
        'm_personnels',
        'm_position',
        'm_programme',
        'm_quartier',
        'm_sousgare',
        'm_sousgareligne',
        'm_tarifs',
        'm_typecaisse',
        'm_type_client',
        'm_type_personnel',
        'm_villes',
    ),
    'Genres' => array(
        'm_entreprises',
        'm_genre_depense',
        'm_genre_depot',
        'm_genre_recette',
    ),
    'Heures' => array(
        'm_entreprises',
        'm_heure',
    ),
    'Historique_Passagers' => array(
        'm_bagage',
        'm_bagageesc',
        'm_bordereaubagage',
        'm_client',
        'm_compagnies',
        'm_comptes_courrier',
        'm_comptes_guichet',
        'm_compte_user',
        'm_courrier_expedier',
        'm_depense',
        'm_depot',
        'm_entreprises',
        'm_envoibagages',
        'm_escalclients',
        'm_heure',
        'm_lignes',
        'm_non_passager',
        'm_ordres',
        'm_passager',
        'm_programme',
        'm_recette',
        'm_report',
        'm_sousgare',
        'm_tamponcode',
        'm_type_client',
        'm_versements',
    ),
    'Historiquesescal' => array(
        'm_compagnies',
        'm_compte_user',
        'm_courrier_expedieresc',
        'm_entreprises',
        'm_expediteur',
        'm_recepteur',
        'm_sousgare',
    ),
    'Home' => array(
        'm_appdossier',
        'm_compagnies',
        'm_compte_user',
        'm_entreprises',
        'm_villes',
    ),
    'Ligneheure' => array(
        'm_compte_user',
        'm_entreprises',
        'm_heure',
        'm_ligne_heure',
        'm_lignes',
        'm_sousgare',
    ),
    'Lignes' => array(
        'm_entreprises',
        'm_gare_arrivee',
        'm_gare_depart',
        'm_itineraire',
        'm_ligne_itineraire',
        'm_lignes',
        'm_itineraire_etape',
        'm_itineraire_escale',
    ),
    'Login' => array(
    ),
    'Menus' => array(
        'm_entreprises',
        'm_menu_bouton',
    ),
    'Pages' => array(
        'm_dossier',
        'm_entreprises',
    ),
    'Personnels' => array(
        'm_client',
        'm_compagnies',
        'm_entreprises',
        'm_personnels',
        'm_type_personnel',
    ),
    'Programmes' => array(
        'm_categories',
        'm_client',
        'm_compagnies',
        'm_compte_user',
        'm_entreprises',
        'm_gare_arrivee',
        'm_itineraire',
        'm_ligne_heure',
        'm_lignes',
        'm_non_passager',
        'm_ordres',
        'm_passager',
        'm_personnels',
        'm_programme',
        'm_programme_correspondance',
        'm_programmebus',
        'm_quartier',
        'm_sousgare',
        'm_sousgareligne',
        'm_tamponcode',
        'm_tamponcodetr',
        'm_tampon_siege',
        'm_tarifications',
        'm_itineraire_etape',
        'm_itineraire_escale',
    ),
    'Rapport' => array(
        'm_bagage',
        'm_bagageesc',
        'm_bon_millitaire',
        'm_bordereaubagage',
        'm_categ',
        'm_compagnies',
        'm_comptes_courrierdepens',
        'm_comptes_courrierrecet',
        'm_comptes_guichet',
        'm_compte_user',
        'm_courrier_expedier',
        'm_courrier_expedieresc',
        'm_courrier_recet',
        'm_depense',
        'm_depot',
        'm_entreprises',
        'm_envoibagages',
        'm_escalclients',
        'm_gare_arrivee',
        'm_gare_depart',
        'm_non_passager',
        'm_ordres',
        'm_passager',
        'm_recette',
        'm_sousgare',
        'm_utilisateur',
        'm_versements',
    ),
    'Recettes' => array(
        'm_caisse',
        'm_client',
        'm_compagnies',
        'm_compte_user',
        'm_entreprises',
        'm_genre_recette',
        'm_personnels',
        'm_recette',
        'm_sousgare',
        'm_typedocument',
        'm_type_personnel',
    ),
    'Reprogrammes' => array(
        'm_bagage',
        'm_bagageesc',
        'm_client',
        'm_code_courrier',
        'm_courrier_expedieresc',
        'm_entreprises',
        'm_escalclients',
        'm_expediteur',
        'm_expedition_reception',
        'm_non_passager',
        'm_passager',
        'm_programme',
        'm_quartier',
        'm_recepteur',
        'm_recupassager',
        'm_report',
        'm_tamponcode',
        'm_tampon_siege',
        'm_itineraire_etape',
    ),
    'Reserves' => array(
        'm_client',
        'm_compte_user',
        'm_entreprises',
        'm_non_passager',
        'm_passager',
        'm_programme',
        'm_sousgare',
        'm_tamponcode',
        'm_tamponcodetr',
        'm_tampon_siege',
        'm_type_client',
        'm_users_role',
        'm_itineraire_etape',
    ),
    'Role_User' => array(
        'm_entreprises',
        'm_users_role',
    ),
    'Statut_Gares' => array(
        'm_compte_user',
        'm_entreprises',
        'm_gare_arrivee',
        'm_gare_heure_statut',
        'm_heure',
        'm_sousgare',
        'm_statut_gare',
    ),
    'Tarifs' => array(
        'm_compte_user',
        'm_entreprises',
        'm_heure',
        'm_ligne_heure',
        'm_sousgare',
        'm_tarifications',
        'm_tarifs',
        'm_type_client',
    ),
    'Ticketfidelite' => array(
        'm_entreprises',
        'm_gare_depart',
        'm_non_passager',
        'm_passager',
    ),
    'Ticket' => array(
        'm_bagage',
        'm_bon_millitaire',
        'm_carte_voyage',
        'm_compagnies',
        'm_entreprises',
        'm_gare_depart',
        'm_liste',
        'm_non_passager',
        'm_passager',
    ),
    'Tick' => array(
        'm_entreprises',
        'm_gare_depart',
        'm_passager',
    ),
    'Types' => array(
        'm_entreprises',
        'm_type_client',
        'm_typedocument',
        'm_type_personnel',
    ),
    'Utilisateurs' => array(
        'm_appdossier',
        'm_autredepense',
        'm_bagage',
        'm_bagageesc',
        'm_caisse',
        'm_compagnies',
        'm_comptes_bagage',
        'm_comptes_courrier',
        'm_comptes_courrierdepens',
        'm_comptes_courrierrecet',
        'm_comptes_guichet',
        'm_compte_user',
        'm_courrier_depens',
        'm_courrier_expedier',
        'm_courrier_expedieresc',
        'm_courrier_recet',
        'm_depense',
        'm_depot',
        'm_dossier',
        'm_entreprises',
        'm_escalclients',
        'm_gare_depart',
        'm_gares',
        'm_genre_depense',
        'm_genre_recette',
        'm_non_passager',
        'm_passager',
        'm_recette',
        'm_report',
        'm_roleattribution',
        'm_sousgare',
        'm_typedocument',
        'm_user_login',
        'm_users_role',
        'm_utilisateur',
        'm_versements',
    ),
    'Ventescales' => array(
        'm_client',
        'm_compte_user',
        'm_entreprises',
        'm_escalclients',
        'm_sousgare',
    ),
    'Villes' => array(
        'm_entreprises',
        'm_pays',
        'm_quartier',
        'm_villes',
    ),
    'Welcome' => array(
        'm_compte_user',
    ),
);
