<?php defined('BASEPATH') OR exit('No direct script access allowed');

/**
 * Sources JS pour bundles caisse / confirmation / bagage.
 * Regénérer : php scripts/build_module_bundles.php
 */
return array(
    'caisse' => array(
        'addrecette.js',
        'adddepense.js',
        'addtrirecette.js',
        'addtrirecettecr.js',
        'addtridepense.js',
        'addtriautredepense.js',
        'addtridepot.js',
        'addtriautredepot.js',
        'addautredepense.js',
        'addepot.js',
        'addautredepot.js',
        'autreadddepot.js',
        'addversebank.js',
        'addverseautre.js',
        'addversefour.js',
        'addversementcaisse.js',
        'upversement.js',
        'adversementcaisse.js',
        'addtriversement.js',
        'addtriclientversement.js',
        'addepotfour.js',
        'adautreupdatedepense.js',
        'recaptrirecette.js',
        'recaptridepense.js',
        'recaptautretridepense.js',
        'recaptridepot.js',
        'recaptriautredepot.js',
        'adreportjs.js',
        'adreportversjs.js',
        'advers.js',
    ),
    'confirmation' => array(
        'filtre_arrivee_compagnie.js',
        'addconfirme.js',
        'addconfirmadmin.js',
        'addconfirmadmintran.js',
        'adventemobile.js',
        'addventemobile.js',
        'addbagage.js',
        'addbagagesuivi.js',
        'addbagagenfact.js',
        'adautrfactbag.js',
        'adventeescale.js',
        'adbagescale.js',
        'adcourescale.js',
        'adpartcoursescale.js',
        'adperscoursescale.js',
        'addsbordesc.js',
        'addreception.js',
        'adreceptperso.js',
        'adsbords.js',
        'adsbordst.js',
        'addbordt.js',
        'adsuivis.js',
        'sadsuivis.js',
        'addbon.js',
        'addcarte.js',
        'addconfirmbon.js',
        'addconfirmcarte.js',
    ),
    'bagage' => array(
        'filtre_arrivee_compagnie.js',
        'addbagage.js',
        'addbagagesuivi.js',
        'addbagagenfact.js',
        'adautrfactbag.js',
        'adbagescale.js',
        'adventeescale.js',
        'adcourescale.js',
        'adpartcoursescale.js',
        'adperscoursescale.js',
        'adsbords.js',
        'adsbordst.js',
        'addbordt.js',
        'adsuivis.js',
        'sadsuivis.js',
        'adreportjsesc.js',
        'adreportglesc.js',
    ),
    'program' => array(
        'addtirage.js',
        'listetirage.js',
        'addvoir.js',
        'addprogramme.js',
        'addgprogramme.js',
        'upprogramme.js',
        'filtre_depart_compagnie.js',
    ),
    'historique' => array(
        'addetat.js',
        'updateticket.js',
        'updateclient.js',
        'updatedticket.js',
    ),
);
